# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jasongen < Formula
  desc "jasongen openapi code generator"
  homepage "https://github.com/jasonhancock/jasongen"
  version "0.0.27"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.27/jasongen_0.0.27_darwin_amd64.tar.gz"
      sha256 "7e46cb26f2c4ef725e90f6f37eb16d3c6247639bee172c310bce9c1e842cb5bb"

      def install
        bin.install "jasongen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.27/jasongen_0.0.27_darwin_arm64.tar.gz"
      sha256 "32f0033b3b13ad42e91d4a917291dcb24fcf6aa9d0e7a9555259c88fd7db1ae4"

      def install
        bin.install "jasongen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.27/jasongen_0.0.27_linux_amd64.tar.gz"
      sha256 "b2f638d263f8e4dd36db8613df2ff1b3a8a3bf3ff487d392579ac5dd24369ccb"
      def install
        bin.install "jasongen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.27/jasongen_0.0.27_linux_arm64.tar.gz"
      sha256 "6059b743acc36b2d868cb045f3e88230c9a9da56aa69642a3ebf2f4d2ac9e194"
      def install
        bin.install "jasongen"
      end
    end
  end
end
