# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jasongen < Formula
  desc "jasongen openapi code generator"
  homepage "https://github.com/jasonhancock/jasongen"
  version "0.0.11"

  on_macos do
    on_intel do
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.11/jasongen_0.0.11_darwin_amd64.tar.gz"
      sha256 "a49ea5547f28d122172c8316dc80f51eae7d0bc282229ce221fdd9bbbaa29e92"

      def install
        bin.install "jasongen"
      end
    end
    on_arm do
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.11/jasongen_0.0.11_darwin_arm64.tar.gz"
      sha256 "bb03b4155d0163a7c543c428885de5d7a03d2751b5e5d0a7f0d903fbfc6309f1"

      def install
        bin.install "jasongen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.11/jasongen_0.0.11_linux_amd64.tar.gz"
        sha256 "7b8abca04ea4f8dec36fa8cd2a6813b49aec6e88353772333a0c016a2a052087"

        def install
          bin.install "jasongen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.11/jasongen_0.0.11_linux_arm64.tar.gz"
        sha256 "493c96ad4bc700404354846919fa4779ebd6566d56133c99231670f6651b50bf"

        def install
          bin.install "jasongen"
        end
      end
    end
  end
end
