# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jasongen < Formula
  desc "jasongen openapi code generator"
  homepage "https://github.com/jasonhancock/jasongen"
  version "0.0.41"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.41/jasongen_0.0.41_darwin_amd64.tar.gz"
      sha256 "d61c8ac49d89126cef17b92da789a2223dc7ccc0c3dfae1e2f2da2b1e473893a"

      define_method(:install) do
        bin.install "jasongen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.41/jasongen_0.0.41_darwin_arm64.tar.gz"
      sha256 "16c635f4bd22601932a70ccadbb6873bce3fabff2e05a255fb899ca1e1a57c53"

      define_method(:install) do
        bin.install "jasongen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.41/jasongen_0.0.41_linux_amd64.tar.gz"
      sha256 "93800ef234d73be8606ec4dfe48d0b2fb727bb9489353bab74b59e0375ec02f5"
      define_method(:install) do
        bin.install "jasongen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jasonhancock/jasongen/releases/download/v0.0.41/jasongen_0.0.41_linux_arm64.tar.gz"
      sha256 "dd3525021cef68450732a0b6d9f6e54d88ef8249099c3c8687e1675f773e40a9"
      define_method(:install) do
        bin.install "jasongen"
      end
    end
  end
end
